server:
  port: 8082
spring:
  application:
    name: ms-bank-account
  data: 
    mongodb:
     host: mongo
     port: 27017
     database: Bank 
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-bank-discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    
client.msbankproductrule.url: http://ms-bank-apigateway:9090/productRule