server:
  port: 8888
  
spring:
  application:
    name: ms-bank-config-server
  cloud:
    config:
      server:
        git:
          cloneOnStart: true
          defaultLabel: file-config-server
          uri: https://github.com/yyayaCalero/nttdata-bootcamp37-file-config-server.git
        bootstrap: true