server:
  port: 8080
spring:
  application:
    name: ms-bank-product
  data: 
    mongodb:
     host: localhost
     port: 27017
     database: Bank 
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true