server:
  port: 9090
spring:
  application:
    name: ms-bank-apigateway
  cloud:
    gateway:
      default-filters:
      - name: SCGWGlobalFilter
      routes:
        - id: ms-bank-product
          uri: http://ms-bank-product:8080/
          predicates:
            - Path=/product/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter
        - id: ms-bank-product-rule
          uri: http://ms-bank-product-rule:8081/
          predicates:
            - Path=/productRule/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter
        - id: ms-bank-account
          uri: http://ms-bank-account:8082/
          predicates:
            - Path=/account/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-bank-discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true


  


