server:
  port: 9090
  address: localhost

spring:
  application:
    name: ms-bank-apigateway
  cloud:
    gateway:
      default-filters:
      - name: SCGWGlobalFilter
      routes:
        - id: ms-bank-product
          uri: http://localhost:8080/
          predicates:
            - Path=/product/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter
        - id: ms-bank-product-rule
          uri: http://localhost:8081/
          predicates:
            - Path=/productRule/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter
        - id: ms-bank-account
          uri: http://localhost:8082/
          predicates:
            - Path=/account/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    instanceId: ${server.address}:${server.port}

  


